//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class currencies
    {
        public int ID { get; set; }
        public Nullable<int> Name { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> Change { get; set; }
        public Nullable<double> ChangePercent { get; set; }
        public Nullable<int> IsChangeDown { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Names Names { get; set; }
    }
}
